version: "3.7"

services:
  keycloak:
    image: jboss/keycloak
    container_name: playtime-keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: "/opt/jboss/import.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - "8081:8080"
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/jboss/import.json

  mongo:
    image: mongo
    container_name: playtime-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: playtime
    ports:
      - "27017:27017"

  mailhog:
    image: mailhog/mailhog
    container_name: playtime-mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui